//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud.DatabaseConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee1
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public string GENDER { get; set; }
        public string ADDRESS { get; set; }
        public string DEPARTMENT { get; set; }
        public Nullable<int> EDID { get; set; }
    
        public virtual Education Education { get; set; }
    }
}
